---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-rbd-pvc
  namespace: busybox-sample
  labels:
    appname: busybox
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ocs-external-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 5Gi
